source data : https://www.kaggle.com/datasets/harishkumardatalab/housing-price-prediction

In [1]:
import numpy as np
import pandas as pd

In [2]:
# import data
data = pd.read_csv("/content/drive/MyDrive/Dataset/Housing.csv")
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,yes,no,yes,no,no,2,no,unfurnished
541,1767150,2400,3,1,1,no,no,no,no,no,0,no,semi-furnished
542,1750000,3620,2,1,1,yes,no,no,no,no,0,no,unfurnished
543,1750000,2910,3,1,1,no,no,no,no,no,0,no,furnished
544,1750000,3850,3,1,2,yes,no,no,no,no,0,no,unfurnished

# EDA

In [ ]:
data.shape

(545, 13)

In [ ]:
data.columns

Index(['price', 'area', 'bedrooms', 'bathrooms', 'stories', 'mainroad',
       'guestroom', 'basement', 'hotwaterheating', 'airconditioning',
       'parking', 'prefarea', 'furnishingstatus'],
      dtype='object')

In [ ]:
data.info()
# Tidak ada data null maupun NaN

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 545 entries, 0 to 544
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   price             545 non-null    int64
 1   area              545 non-null    int64
 2   bedrooms          545 non-null    int64
 3   bathrooms         545 non-null    int64
 4   stories           545 non-null    int64
 5   mainroad          545 non-null    object
 6   guestroom         545 non-null    object
 7   basement          545 non-null    object
 8   hotwaterheating   545 non-null    object
 9   airconditioning   545 non-null    object
 10  parking           545 non-null    int64
 11  prefarea          545 non-null    object
 12  furnishingstatus  545 non-null    object
dtypes: int64(6), object(7)
memory usage: 55.5+ KB

In [ ]:
for i in data.columns :
  print(data[i].value_counts())

price
3500000     17
4200000     17
4900000     12
3150000      9
5600000      9
            ..
6580000      1
4319000      1
4375000      1
4382000      1
13300000     1
Name: count, Length: 219, dtype: int64
area
6000    24
3000    14
4500    13
4000    11
5500     9
        ..
6862     1
4815     1
9166     1
6321     1
3620     1
Name: count, Length: 284, dtype: int64
bedrooms
3    300
2    136
4     95
5     10
6      2
1      2
Name: count, dtype: int64
bathrooms
1    401
2    133
3     10
4      1
Name: count, dtype: int64
stories
2    238
1    227
4     41
3     39
Name: count, dtype: int64
mainroad
yes    468
no      77
Name: count, dtype: int64
guestroom
no     448
yes     97
Name: count, dtype: int64
basement
no     354
yes    191
Name: count, dtype: int64
hotwaterheating
no     520
yes     25
Name: count, dtype: int64
airconditioning
no     373
yes    172
Name: count, dtype: int64
parking
0    299
1    126
2    108
3     12
Name: count, dtype: int64
prefarea
no     417
yes    128
Name: count, dtype: int64
furnishingstatus
semi-furnished    227
unfurnished       178
furnished         140
Name: count, dtype: int64

# Feature Engineering

In [3]:
# Binary Encoding
data_encode = {"mainroad" : {"yes":1,"no":0}}
data = data.replace(data_encode)
data_encode = {"guestroom" : {"yes":1,"no":0}}
data = data.replace(data_encode)
data_encode = {"basement" : {"yes":1,"no":0}}
data = data.replace(data_encode)
data_encode = {"hotwaterheating" : {"yes":1,"no":0}}
data = data.replace(data_encode)
data_encode = {"airconditioning" : {"yes":1,"no":0}}
data = data.replace(data_encode)
data_encode = {"prefarea" : {"yes":1,"no":0}}
data = data.replace(data_encode)

In [4]:
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,furnished
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,furnished
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,semi-furnished
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,furnished
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,furnished
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,unfurnished
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,semi-furnished
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,unfurnished
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,furnished
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,unfurnished

In [5]:
# Label Encoding
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()

In [6]:
data["furnishingstatus"]=LE.fit_transform(data["furnishingstatus"])

In [7]:
data

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,1,0,0,0,1,2,1,0
1,12250000,8960,4,4,4,1,0,0,0,1,3,0,0
2,12250000,9960,3,2,2,1,0,1,0,0,2,1,1
3,12215000,7500,4,2,2,1,0,1,0,1,3,1,0
4,11410000,7420,4,1,2,1,1,1,0,1,2,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
540,1820000,3000,2,1,1,1,0,1,0,0,2,0,2
541,1767150,2400,3,1,1,0,0,0,0,0,0,0,1
542,1750000,3620,2,1,1,1,0,0,0,0,0,0,2
543,1750000,2910,3,1,1,0,0,0,0,0,0,0,0
544,1750000,3850,3,1,2,1,0,0,0,0,0,0,2

In [ ]:
# Cek kembali data
for i in data.columns:
  print(data[i].value_counts())

price
3500000     17
4200000     17
4900000     12
3150000      9
5600000      9
            ..
6580000      1
4319000      1
4375000      1
4382000      1
13300000     1
Name: count, Length: 219, dtype: int64
area
6000    24
3000    14
4500    13
4000    11
5500     9
        ..
6862     1
4815     1
9166     1
6321     1
3620     1
Name: count, Length: 284, dtype: int64
bedrooms
3    300
2    136
4     95
5     10
6      2
1      2
Name: count, dtype: int64
bathrooms
1    401
2    133
3     10
4      1
Name: count, dtype: int64
stories
2    238
1    227
4     41
3     39
Name: count, dtype: int64
mainroad
1    468
0     77
Name: count, dtype: int64
guestroom
0    448
1     97
Name: count, dtype: int64
basement
0    354
1    191
Name: count, dtype: int64
hotwaterheating
0    520
1     25
Name: count, dtype: int64
airconditioning
0    373
1    172
Name: count, dtype: int64
parking
0    299
1    126
2    108
3     12
Name: count, dtype: int64
prefarea
0    417
1    128
Name: count, dtype: int64
furnishingstatus
1    227
2    178
0    140
Name: count, dtype: int64

# Modelling

In [8]:
from sklearn.tree import DecisionTreeRegressor
from sklearn.model_selection import train_test_split

In [9]:
x = data.drop("price", axis=1)
y = data["price"]

In [10]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

In [11]:
DT = DecisionTreeRegressor()

In [12]:
DT.fit(x_train, y_train)

DecisionTreeRegressor()

In [13]:
y_pred = DT.predict(x_test)

In [14]:
from sklearn import metrics
from sklearn.metrics import r2_score, mean_absolute_error

In [15]:
# Cek akurasi
print(r2_score(y_pred, y_test))

0.31019061197605324

# Test menggunakan data baru

In [17]:
data_baru = {"area" : [3645],
             "bedrooms" : [2],
             "bathrooms"	: [1],
             "stories" : [2],
             "mainroad" : [1],
             "guestroom" : [0],
             "basement" : [1],
             "hotwaterheating" : [0],
             "airconditioning" : [1],
             "parking" : [3],
             "prefarea" : [1],
             "furnishingstatus" : [0]}

In [18]:
data_baru = pd.DataFrame(data_baru)

In [19]:
prediksi = DT.predict(data_baru)

In [20]:
prediksi

array([4098500.])